### ISSUE TITLE
Debugging tests through this plugin?

### ISSUE THREAD

**Issue by hkcountryman** [OpenLiberty/open-liberty-tools-vscode#108]
I don't know if I'm just missing something or if there's a good way to do this, but I would love to be able to debug tests and I didn't see that option available.

There's not much context to this one since it's a feature request I suppose, but for what it's worth I am using Maven and right-clicked on my server in the Liberty dev dashboard, then checked the docs for an explanation of what the options in the right-click menu were. I didn't see one that looked like an obvious way to debug tests. I also checked whether this extension somehow interacted with the [test runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) and the [Maven support extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven) but nothing jumped out at me.

I believe the reason the test runner for Java plugin doesn't work for me has to do with variables set in pom.xml and server.xml - for instance, I attempted to run the tests in [this guide](https://github.com/OpenLiberty/guide-cors) but the default ports specified in the `<liberty.var. ... >` tags in pom.xml were null, so my tests failed. Evidently the way to debug Maven goals in VS Code is to right-click on the goals in the panel added by the Maven support extension, but there doesn't seem to be a goal to ONLY test liberty, I suppose since it needs to be run before tests can happen. So I thought an extension for Open Liberty projects might be a way to patch that, though it could also be me setting up Maven in VS Code wrong!

**Comment by hkcountryman** [comment]
Thank you @kathrynkodama! I'm not sure I understand what you mean by step 3, "attach your debugger and add break-points to your test code" - the way I tried was to start Liberty through the dev dashboard, then click on "Attach to remote program (start)" at the bottom of this screenshot:

![image](https://user-images.githubusercontent.com/62478826/179550391-060743dd-dbc0-43e0-8c25-c7547cea623c.png)

This opens the command palette where I once again choose "Attach to remote program" and that starts debugging mode with the buttons to pause, step, restart, detach, etc. at the top. However, when I run my tests through the dev dashboard, it ignores my breakpoints inside my tests. You can see here it simply runs the tests in the integrated terminal instead of pausing on line 41:

![image](https://user-images.githubusercontent.com/62478826/179551355-78852018-4c62-4dc0-8f98-504dd4efeb93.png)

However, I did find an alternate solution that I'll share in case it's helpful in adding functionality to the plugin or in case someone runs into the same issue I did. I noticed that I can skip the Liberty dev dashboard and instead type directly into the integrated terminal `mvnDebug -DforkCount=0 liberty:dev` so that I can use Maven's debug port on 8000. So my launch.json now includes both:

```json
    {
      "type": "java",
      "name": "Debug (Attach)",
      "request": "attach",
      "hostName": "localhost",
      "port": 8000
    },
    {
      "type": "java",
      "name": "Attach to remote program",
      "request": "attach",
      "hostName": "localhost",
      "port": 7777
    }
```

(By the way, I did try your example where the port numbers are strings, and it made no difference. Here they are numbers because that's what the VS Code docs show, but I think either works.)

When running with `mvnDebug` and attaching my "Debug (Attach)" debugger, Liberty successfully starts in dev mode and I can press enter while in the terminal to start tests. Then VS Code will pause on my breakpoints:

![image](https://user-images.githubusercontent.com/62478826/179553084-fadbf6ec-bee2-4cd2-a408-16ca205ce3be.png)

As it turns out, when using this method Maven does correctly pick up the variables specified in server.xml, so I am able to use the integrated debugger.

Please let me know if I misunderstood something from your instructions since it's definitely very convenient to be able to do everything with one tool so it would be nice to be able to run tests using the dev dashboard if that's an option, but for now I'm satisfied that I've found a way to debug my tests so I'll close this issue. Thank you for the help!

**Comment by kathrynkodama** [comment]
Glad you found a way that worked @hkcountryman! Just to clarify what I meant above, once you start dev mode you can connect the VS Code debugger to port `7777`. Your launch.json should only need to include the one configuration:
```
        {
            "type": "java",
            "name": "Attach to Remote Program",
            "request": "attach",
            "hostName": "localhost",
            "port": "7777"
        }
```
Then you can attach the debugger by going to the "Run and debug" tab on the left and clicking on the "Attach to remote program":
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/26146482/179571984-cfe9522b-6bfd-405d-a451-1bf76fde6c60.png">

Then, selecting "Run Tests" from the dev mode dashboard, you should see in the dev mode dashboard tests starting to run and the VS Code debugger should pause at the breakpoints you specified.

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/26146482/179570780-d2f687b0-af06-45e8-96ae-35523f5d9843.png">

This video might help as well, it showcases how to attach the debugger to your Liberty application in VS Code: https://www.youtube.com/watch?v=6wJRxUGdNRM&t=260s

**Comment by hkcountryman** [comment]
I see, thank you! I was able to use the debugger with the method shown in the video. The only thing I could not do was use the variables set in pom.xml and server.xml, which could be a limitation or it could be that I need to do extra configuration to access those variables.

In case it's the former and this is helpful, for context I was following [this guide on setting up cors](https://openliberty.io/guides/cors.html) - a test evaluates `System.getProperty("default.http.port")` which is one of those Liberty variables, but that expression is null so the test fails. Looking through the VS Code docs I would guess another solution might be [using "vmArgs" or "env"](https://code.visualstudio.com/docs/java/java-testing#_customize-test-configurations) in the test configuration.
