### ISSUE TITLE
Multi module projects with a nested valid pom.xml do not show up in the dashboard

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/open-liberty-tools-vscode#61]
For reference look at this project: https://github.com/OpenLiberty/guide-maven-multimodules

In the /finish/ear folder there exists a `pom.xml` with the `liberty-maven-plugin` defined in it. This should be picked up by the dashboard and display the corresponding project.  Currently the dashboard is empty. 

![image](https://user-images.githubusercontent.com/26146482/87447276-619c8480-c5c8-11ea-8efd-bb1ed897349a.png)

**Comment by ericglau** [comment]
This should be considered as part of https://github.com/OpenLiberty/ci.maven/issues/697

**Comment by kathrynkodama** [comment]
Closing as this is currently picked up, but #98 still needs to addressed
<img width="489" alt="image" src="https://user-images.githubusercontent.com/26146482/181363651-a83c5c5a-0d65-46f3-ad90-ad0f5839e3f6.png">
